[default]
src = 'contracts'
out = 'out'
libs = ['lib']
test = 'test'
remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@prb/test/=lib/prb-test/src/',
    '@webb-tools/protocol-solidity=node_modules/@webb-tools/protocol-solidity/',
    'forge-std/=lib/forge-std/src/',
    'src/=src/',
]
